version: "3"

services:
  nginx:
    build:
      context: ../../nginx
    depends_on:
      - db
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ../../nginx/log:/var/log/nginx
    environment:
      - WAIT_HOSTS=db:3306

  db:
    build:
      context: ../../db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - db-data:/var/lib/mysql

  wordpress:
    build:
      context: ../../wordpress
    volumes:
      - ../../../wordpress:/var/www/myblog

  adminer:
    image: adminer
    ports:
      - 28080:8080

volumes:
  db-data:
