version: "3"

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: app
      WORDPRESS_DB_PASSWORD: app
      WORDPRESS_DB_NAME: blog
    volumes:
      - wordpress:/var/www/html
      - ../../../test:/test

  db:
    build:
      context: ../../db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 28080:8080

volumes:
  db-data:
  wordpress:
