version: "3"

services:
  server:
    build:
      context: ../../nginx
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      # - ../../nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../nginx/log:/var/log/nginx
      - ../../../Wordpress:/var/www/
    environment:
      - WAIT_HOSTS=db:3306

  db:
    build:
      context: ../../db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 28080:8080

volumes:
  db-data:
